import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<header>
          <nav>
            <ul>
              <li>
                <Link href="/">Accueil</Link>
              </li>
              <li>
                <Link href="/about">À propos</Link>
              </li>
              <li>
                <Link href="/contacts">Contacts</Link>
              </li>
              <li>
                <Link href="/articles">Articles</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>

        <footer>
          <p>© 2024 Mon Blog - Tous droits réservés</p>
        </footer>
        
      </body>
    </html>
  );
}
